hyp3_rtc_gamma/__main__.py
This keeps the containerized version (here) and the legacy version in sync.
=> Add new matching option from cloud-proj

hyp3_rtc_gamma/__main__.py
=> Write entry stript to select appropriate hyp3 version

hyp3_rtc_gamma/__main__.py, hyp3_rtc_gamma/rtc_sentinel.py
=> move log setup into rtc_sentinel

tests/test_entrypoints.py
=> test new entry and v2 entrypoints

tests/test_v2.py
=> add unit tests for v2 helper functions

hyp3_rtc_gamma/__main__.py, tests/test_v2.py
=> have main_v2() zip output directory before uploading to s3

hyp3_rtc_gamma/__main__.py, setup.py
This adds a retry policy to the download file function so that minor http errors and faults might be resolved automatically.
=> added retry policy to downloads to increase fault tolerence

hyp3_rtc_gamma/create_metadata.py
=> APD-1473: rename readme file

hyp3_rtc_gamma/create_metadata.py
=> rename readme to .txt

hyp3_rtc_gamma/rtc_sentinel.py
No functional changes yet, just eliminating redundant variables related to the product name before actually implementing any changes.
=> refactor out_name handling in rtc_sentinel

conda-env.yml, hyp3_rtc_gamma/rtc_sentinel.py, setup.py
https://github.com/asfadmin/hyp3-lib/blob/develop/CHANGELOG.md#v130
Haven't run this yet, will do a due-diligence run before marking ready for merge.
=> update to hyp3-lib 1.3.0

hyp3_rtc_gamma/etc/README_RTC_GAMMA.txt
=> Revise description of browse images in readme

hyp3_rtc_gamma/__main__.py
Adds browse image to s3 bucket
=> Add Browse image to S3 Bucket

hyp3_rtc_gamma/__main__.py, tests/test_v2.py
=> drop extra . in thumbnail file names

CHANGELOG.md, hyp3_rtc_gamma/__main__.py, tests/test_v2.py
* ~"major" -- Major changes to the API that may break current workflows
* ~"minor" -- Minor changes to the API that do not break current workflows 
* **~"patch"** -- Patches and bugfixes for the current version that do not break current workflows
* ~"bumpless" -- Changes to documentation, CI/CD pipelines, etc. that don't affect the software's version
=> Release: thumbnail filename fix

.github/PULL_REQUEST_TEMPLATE/release.md, conda-env.yml, hyp3_rtc_gamma/__main__.py, hyp3_rtc_gamma/etc/README_RTC_GAMMA.txt, hyp3_rtc_gamma/rtc_sentinel.py, setup.py, tests/test_rtc_sentinel.py, tests/test_v1.py, tests/test_v2.py
=> Implement new product naming scheme

hyp3_rtc_gamma/rtc_sentinel.py, tests/test_rtc_sentinel.py
=> address floating point resolutions in naming scheme

hyp3_rtc_gamma/etc/README_RTC_GAMMA.txt, hyp3_rtc_gamma/rtc_sentinel.py, tests/test_rtc_sentinel.py
=> update naming readme, use 4 character id instead of 6

.github/workflows/test-and-build.yml, conda-env.yml, setup.py
=> Don't duplicate conda channels and use conda hyp3lib

hyp3_rtc_gamma/rtc_sentinel.py
=> remove _diff.par file from output zip

hyp3_rtc_gamma/etc/README_RTC_GAMMA.txt
Applying ./hyp3-rtc-gamma-55531fe.patch, see:
https://github.com/ASFHyP3/hyp3-metadata-templates/compare/9a1743f9cbce0fecb9aabc4888bff53b97a8f8b0..55531fed11200d74471693fe0bc83cc922b6be91
=> Update metadata templates

hyp3_rtc_gamma/rtc_sentinel.py, tests/test_rtc_sentinel.py
=> Name revisions

hyp3_rtc_gamma/rtc_sentinel.py, tests/test_rtc_sentinel.py
=> refactor how to determine which polarizations to process

hyp3_rtc_gamma/__main__.py, hyp3_rtc_gamma/rtc_sentinel.py
=> eliminate lo_flag, set default resolution to 30.0

hyp3_rtc_gamma/__main__.py
=> Add customization parameters to v2 entrypoint

hyp3_rtc_gamma/__init__.py
=> Print install warning when package import fails

README.md
=> add cursory developer setup instructions to readme

.github/workflows/release.yml
=> Add needed space in release title prefix

CHANGELOG.md
=> update changelog for v2.3.0 release

Dockerfile, conda-env.yml, setup.py
=> remove obsolete scipy dependency

hyp3_rtc_gamma/__main__.py, tests/test_v2.py
=> Browse priority

hyp3_rtc_gamma/__main__.py, hyp3_rtc_gamma/rtc_sentinel.py
=> move rename of PRODUCT directory into rtc_sentinel

CHANGELOG.md
=> update changelog for v2.3.1 release

hyp3_rtc_gamma/rtc_sentinel.py
=> remove thumbnail image from ls_map xml

CHANGELOG.md
=> add changelog entry for removal of ls_map thumbnail

.github/workflows/labeled-pr.yml
=> add github action to check for labels on production release PRs

.github/workflows/changelog.yml, CHANGELOG.md, conda-env.yml, setup.py
=> add changelog github action, upgrade hyp3_metadata version

CHANGELOG.md, conda-env.yml, setup.py
=> upgrade to hyp3lib v1.6.1

CHANGELOG.md, conda-env.yml, setup.py
The v1 hyp3-test, then hyp3, databases should be updated post-release: `update processes set image = '626226570674.dkr.ecr.us-east-1.amazonaws.com/hyp3-rtc-gamma:2.3.3' where id = 2 and text_id = 'rtc_gamma';`
* ~"major" -- Major changes to the API that may break current workflows
* ~"minor" -- Minor changes to the API that do not break current workflows
* **~"patch" -- Patches and bugfixes for the current version that do not break current workflows**
* ~"bumpless" -- Changes to documentation, CI/CD pipelines, etc. that don't affect the software's version
=> Release: v2.3.3

CHANGELOG.md, conda-env.yml, setup.py
=> upgrade to hyp3lib v1.6.2

CHANGELOG.md, conda-env.yml, setup.py
* ~"major" -- Major changes to the API that may break current workflows
* ~"minor" -- Minor changes to the API that do not break current workflows
* **~"patch" -- Patches and bugfixes for the current version that do not break current workflows**
* ~"bumpless" -- Changes to documentation, CI/CD pipelines, etc. that don't affect the software's version
=> Release: v2.3.4

CHANGELOG.md, conda-env.yml, setup.py
=> upgrade to hyp3_metadata v0.1.3

CHANGELOG.md
=> Update changelog with fix of #179

.github/workflows/test-and-build.yml, hyp3_rtc_gamma/rtc_sentinel.py
=> fix "file not found" error for area map when generating browse images

.github/workflows/test-and-build.yml, CHANGELOG.md, conda-env.yml, hyp3_rtc_gamma/rtc_sentinel.py, setup.py
=> Radcal2 nov

CHANGELOG.md, conda-env.yml, hyp3_rtc_gamma/rtc_sentinel.py, setup.py
=> Release mk_geo_radcal2 upgrade

hyp3_gamma/rtc/rtc_sentinel.py
=> capture both co-pol and cross-pol mk_geo_radcal mode 3 log files

CHANGELOG.md, conda-env.yml, hyp3_gamma/insar/ifm_sentinel.py, hyp3_gamma/rtc/rtc_sentinel.py, setup.py
=> Upgrade hyp3_metadata to 0.2

hyp3_gamma/rtc/coregistration.py, hyp3_gamma/rtc/rtc_sentinel.py
=> make GAMMA upper-case in rtc.coregistration docstring

CHANGELOG.md
=> changelog for removal of util.find_and_remove()

hyp3_gamma/insar/interf_pwr_s1_lt_tops_proc.py
=> Removing extra line of code.

CHANGELOG.md, hyp3_gamma/insar/ifm_sentinel.py, hyp3_gamma/insar/unwrapping_geocoding.py
=> Add wrapped phase to output file collection

.github/workflows/test-and-build.yml
=> Update Saftey ignores

.github/workflows/test-and-build.yml, CHANGELOG.md, hyp3_gamma/insar/ifm_sentinel.py, hyp3_gamma/insar/interf_pwr_s1_lt_tops_proc.py, hyp3_gamma/insar/unwrapping_geocoding.py
=> Release: v4.0.1

.github/workflows/test-and-build.yml, CHANGELOG.md, conda-env.yml, setup.py
=> Upgrade to hyp3lib v1.6.4, remove safety

.github/workflows/test-and-build.yml, CHANGELOG.md, conda-env.yml, setup.py
Golden tests both pass
RTC - https://github.com/ASFHyP3/hyp3-testing/actions/runs/570585250
InSAR - https://github.com/ASFHyP3/hyp3-testing/actions/runs/570585462
=> Release upgrade to hyp3lib v1.6.4

CHANGELOG.md, hyp3_gamma/insar/ifm_sentinel.py, tests/insar/test_ifm_sentinel.py
=> fix off-by-one error in days of separation for InSAR product names

CHANGELOG.md, hyp3_gamma/insar/ifm_sentinel.py, tests/insar/test_ifm_sentinel.py
=> Release InSAR product name fix

CHANGELOG.md, hyp3_gamma/rtc/rtc_sentinel.py
SLC with predicted orbit: https://asj-hyp3-dev.s3-us-west-2.amazonaws.com/S1A_IW_20150621T120220_SVO_RTC30_G_gpuned_AB65.zip
Same SLC with precision orbit: https://asj-hyp3-dev.s3-us-west-2.amazonaws.com/S1A_IW_20150621T120220_SVP_RTC30_G_gpuned_A32B.zip
Dual pol GRDH also runs as expected with predicted orbit.
=> proceed with rtc processing when no orbit file found

CHANGELOG.md, hyp3_gamma/rtc/rtc_sentinel.py
Still pending completion of golden tests for RTC and InSAR.
=> Release rtc using predicted orbits

CHANGELOG.md, conda-env.yml, hyp3_gamma/__main__.py, setup.py
=> uploaded unzipped rtc product

CHANGELOG.md, conda-env.yml, hyp3_gamma/__main__.py, setup.py
=> Release upload of unzipped RTC files

hyp3_gamma/rtc/rtc_sentinel.py
=> re-implement conversion of output dem from Float32 to Int16

CHANGELOG.md
=> update changelog for 4.1.0 release

CHANGELOG.md, hyp3_gamma/insar/ifm_sentinel.py
=> Proceed without precise orbits

CHANGELOG.md, conda-env.yml, setup.py
=> upgrade to hyp3lib v1.6.7

CHANGELOG.md, conda-env.yml, hyp3_gamma/insar/ifm_sentinel.py, setup.py
=> Release S1 orbit improvements

CHANGELOG.md, hyp3_gamma/insar/ifm_sentinel.py
=> InSAR require restituded or precision orbits

CHANGELOG.md, hyp3_gamma/insar/ifm_sentinel.py
=> Release requiring orbits for InSAR again

CHANGELOG.md, conda-env.yml, setup.py
=> upgrade to hyp3-metadata v0.4.0

.github/workflows/static-analysis.yml, .github/workflows/test-and-build.yml, hyp3_gamma/dem.py, hyp3_gamma/util.py, tests/test_dem.py, tests/test_util.py
=> Move GDALConfigManager to util, add docstring for prepare_dem_geotiff

CHANGELOG.md, conda-env.yml, hyp3_gamma/rtc/rtc_sentinel.py, setup.py
=> update to hyp3-metadata-templates v0.4.1

CHANGELOG.md
=> update changelog for v4.2.0 release

CHANGELOG.md, conda-env.yml, setup.py
=> upgrade to hyp3_metadata v0.4.2

README.md
=> use python -m pip in readme example

.github/workflows/static-analysis.yml, .github/workflows/test-and-build.yml, CHANGELOG.md, README.md, conda-env.yml, hyp3_gamma/__main__.py, hyp3_gamma/dem.py, hyp3_gamma/rtc/rtc_sentinel.py, hyp3_gamma/util.py, setup.py, tests/data/alaska.kml, tests/data/antimeridian.kml, tests/test_dem.py, tests/test_util.py
[InSAR golden test](https://github.com/ASFHyP3/hyp3-testing/actions/runs/721292562) passes compared to prod.
[RTC golden test](https://github.com/ASFHyP3/hyp3-testing/actions/runs/721292402) passes compared to prod except for the addition of the rgb.tif.xml file, as expected.  This only test only exercises the `dem_name='legacy'` option, since `dem_name='copernicus'` is not available in prod to compare against.
=> Release 4.2.0: Copernicus DEM and metadata improvements for RTC

CHANGELOG.md
=> pin version number for 4.3.0 release

CHANGELOG.md, hyp3_gamma/dem.py, hyp3_gamma/insar/create_metadata_insar_gamma.py, hyp3_gamma/insar/etc/README_InSAR_GAMMA.txt, hyp3_gamma/insar/getDemFileGamma.py, hyp3_gamma/insar/ifm_sentinel.py, tests/test_dem.py
=> Release Copernicus DEM for InSAR

hyp3_gamma/__main__.py
This was way less interesting than I expected.
=> add --include-inc-map parameter to hyp3 insar entrypoint

CHANGELOG.md, hyp3_gamma/__main__.py, hyp3_gamma/insar/ifm_sentinel.py
=> Final polish for incidence angle parameter

hyp3_gamma/insar/etc/README_InSAR_GAMMA.txt
=> stylize GeoTIFF in inc map description in readme

CHANGELOG.md, hyp3_gamma/__main__.py, hyp3_gamma/insar/etc/README_InSAR_GAMMA.txt, hyp3_gamma/insar/ifm_sentinel.py, hyp3_gamma/insar/unwrapping_geocoding.py
=> Release inc map and new metadata attributes for InSAR

CHANGELOG.md, hyp3_gamma/__main__.py, hyp3_gamma/insar/etc/README_InSAR_GAMMA.txt, hyp3_gamma/insar/getDemFileGamma.py, hyp3_gamma/insar/ifm_sentinel.py, hyp3_gamma/insar/water_mask.py
=> Water masking for InSAR

hyp3_gamma/insar/ifm_sentinel.py, tests/insar/test_ifm_sentinel.py
=> update insar product name based on water mask option

hyp3_gamma/insar/etc/README_InSAR_GAMMA.txt
=> Fix two readme typos

hyp3_gamma/__main__.py
=> fix argpase typo for __main__.insar

CHANGELOG.md
=> add missing diff links to changelog

CHANGELOG.md, hyp3_gamma/__main__.py, hyp3_gamma/insar/etc/README_InSAR_GAMMA.txt
=> Release include_wrapped_phase option for InSAR jobs

Dockerfile
=> add conda to path so that __main__.py can invoke it through subprocess

hyp3_gamma/__main__.py, hyp3_gamma/insar/ifm_sentinel.py
=> remove safe off of the reference granule in metadata

CHANGELOG.md
=> update changelog; 4.6.0 is the next release

.github/workflows/release.yml, CHANGELOG.md, conda-env.yml, setup.py
=> upgrade to hyp3_metadata v1.2.2

CHANGELOG.md, conda-env.yml, setup.py
=> upgrade to hyp3_metadata v1.2.3

.github/pull_request_template.md, .github/workflows/changelog.yml, .github/workflows/labeled-pr.yml, .github/workflows/release.yml, .github/workflows/test-and-build.yml
=> Master --> main

CHANGELOG.md, environment.yml, setup.py
=> upgrade to hyp3-lib 1.6.8 for nan value bug

CHANGELOG.md
=> changelog tweaks for 4.6.1 release

CHANGELOG.md, environment.yml, setup.py
=> upgrade to hyp3_metadata v1.2.4

hyp3_gamma/insar/water_mask.py
=> set metadata AERA_OR_POINT to "Point" for the water_mask.tif

Dockerfile, environment.yml, hyp3_gamma/water_mask.py, setup.py
=> use geopandas to subset shapefile prior to creating water mask

CHANGELOG.md, environment.yml, setup.py
This bring in README and xml changes documenting the new ellipsoid incidence angle GeoTIFF.
=> Upgrade to hyp3_metadata v1.2.5

CHANGELOG.md, hyp3_gamma/dem.py, hyp3_gamma/insar/ifm_sentinel.py
=> tweak changelog, parameter help for include_inc_map option

CHANGELOG.md, environment.yml, hyp3_gamma/insar/ifm_sentinel.py, hyp3_gamma/insar/unwrapping_geocoding.py, setup.py
=> Release v4.6.3

CHANGELOG.md, environment.yml, hyp3_gamma/__main__.py, hyp3_gamma/insar/ifm_sentinel.py, hyp3_gamma/insar/unwrapping_geocoding.py, setup.py, tests/insar/test_ifm_sentinel.py
Will pull in the the upcoming 1.3.0 release of `hyp3_datadata` with the water mask applied description (ASFHyP3/hyp3-metadata-templates#110).
=> Water mask applied metadata

hyp3_gamma/insar/ifm_sentinel.py
=> use NearestNeighbour when calling makeAsfBrowse() in the ifm_sentinel.py

hyp3_gamma/insar/unwrapping_geocoding.py
=> fix fringes in unw_phase browse image

.github/workflows/test-and-build.yml, CHANGELOG.md, Dockerfile, README.md, environment.yml, hyp3_gamma/__init__.py, hyp3_gamma/insar/ifm_sentinel.py, hyp3_gamma/insar/interf_pwr_s1_lt_tops_proc.py, hyp3_gamma/insar/unwrapping_geocoding.py, setup.py
=> Release GAMMA 20210701 Upgrade

CHANGELOG.md, hyp3_gamma/rtc/rtc_sentinel.py
=> fix pathing error in rtc_sentinel.py (#332)

CHANGELOG.md, hyp3_gamma/rtc/rtc_sentinel.py
RTC golden test passes at https://github.com/ASFHyP3/hyp3-testing/actions/runs/1551729111
=> Release v5.1.2

.github/workflows/test-and-build.yml
Duplicating ASFHyP3/actions#8 here since we can't use the re-usable workflows due to GAMMA shenanigans.
=> fetch tags for in-docker package build

CHANGELOG.md, hyp3_gamma/insar/unwrapping_geocoding.py
=> Cc pwr thres v2

CHANGELOG.md, hyp3_gamma/insar/unwrapping_geocoding.py
Reverts ASFHyP3/hyp3-gamma#338
Should look the opposite of: https://github.com/ASFHyP3/hyp3-gamma/compare/main...develop
=> Revert "Cc pwr thres v2"

CHANGELOG.md, hyp3_gamma/dem.py, hyp3_gamma/insar/unwrapping_geocoding.py, tests/test_dem.py
=> Release v5.1.4 - us-west-2 dem

CHANGELOG.md, hyp3_gamma/insar/unwrapping_geocoding.py
=> test getting rid of power threshold when calcualting vadility mask

CHANGELOG.md, hyp3_gamma/insar/unwrapping_geocoding.py
Reverts ASFHyP3/hyp3-gamma#347
=> Revert "test getting rid of power threshold when calcualting vadility mask"

CHANGELOG.md, environment.yml, setup.py
=> upgrade to hyp3lib v1.7.0

CHANGELOG.md, environment.yml, hyp3_gamma/insar/unwrapping_geocoding.py, setup.py
=> Release v5.1.5

CHANGELOG.md, Dockerfile
=> Release v5.1.6

CHANGELOG.md, Dockerfile
=> point to asf-tools latest image

CHANGELOG.md, Dockerfile
=> Release v5.1.7: ASF-Tools Docker Image

CHANGELOG.md, Dockerfile
=> Release v5.1.8

CHANGELOG.md
=> Add more detail to changelog entry for InSAR updates

CHANGELOG.md, hyp3_gamma/insar/unwrapping_geocoding.py
We did the test and golden test. From the test, We compare the results produced by develop branch code to those by prod code. They basically are very close each other. There are some different in a few arbitrary areas where exist phase jumps.  Golden test shows there are 2 of 32 files does not pass the threshold test. By checking the two failed files, we found the same  results as they are derived from the test. So we think the PR is good enough to be merged into main branch.
=> report the reference point starting from 0 to the output text file

hyp3_gamma/__main__.py
=> Change estimtaor to iterative

CHANGELOG.md, Dockerfile, hyp3_gamma/__main__.py, setup.py
=> Add flood maps

hyp3_gamma/__main__.py
=> Switch underscores to dashes

hyp3_gamma/__main__.py
=> Update it bounds to 2 args

CHANGELOG.md, Dockerfile, hyp3_gamma/__main__.py
=> Release v5.3.0

CHANGELOG.md
=> Replaced updated with changed in changelog

CHANGELOG.md, Dockerfile
=> Update asf-tools v0.4.1

CHANGELOG.md, Dockerfile, hyp3_gamma/__main__.py
=> Add VV Raster input for FM

CHANGELOG.md, Dockerfile, hyp3_gamma/__main__.py
=> Release v5.4.3

CHANGELOG.md, hyp3_gamma/__main__.py
=> save all product files to s3 bucket

CHANGELOG.md, hyp3_gamma/__main__.py
=> insar now uploads unzipped product files (in addition to the zip archive) when using the --bucket option

CHANGELOG.md, hyp3_gamma/__main__.py
=> Remove initial/fuzzy geotiffs from water_map product package

CHANGELOG.md, hyp3_gamma/__main__.py
=> Release v5.4.5

.github/workflows/test-and-build.yml
=> use correct gamma ubuntu2004 installer

.github/workflows/test-and-build.yml, CHANGELOG.md, Dockerfile, environment.yml, setup.py
=> refactor 22.04 build

.github/dependabot.yml, .github/workflows/changelog.yml, .github/workflows/labeled-pr.yml, .github/workflows/release.yml, .github/workflows/static-analysis.yml, .github/workflows/tag-version.yml, .github/workflows/test-and-build.yml
=> automate version updates for github actions

Dockerfile
=> Update asf-tools to v0.4.3

CHANGELOG.md
=> update changelog for v5.7.1

.github/dependabot.yml, .github/workflows/changelog.yml, .github/workflows/labeled-pr.yml, .github/workflows/release.yml, .github/workflows/static-analysis.yml, .github/workflows/tag-version.yml, .github/workflows/test-and-build.yml, CHANGELOG.md, Dockerfile, environment.yml, hyp3_gamma/__main__.py, setup.py
=> Release v5.7.1

CHANGELOG.md, Dockerfile
=> upgrade to asf-tools v 0.4.4

CHANGELOG.md
=> update changelog for 5.7.2 release

CHANGELOG.md, Dockerfile, environment.yml
=> Release v5.7.2

CHANGELOG.md, hyp3_gamma/metadata/rtc.py, tests/metadata/test_rtc_gamma.py
=> add decibel in the README.md.txt when the product is with decibel option

.github/workflows/changelog.yml, .github/workflows/labeled-pr.yml, .github/workflows/release.yml, .github/workflows/static-analysis.yml, .github/workflows/tag-version.yml, .github/workflows/test-and-build.yml
=> Try upgrading actions

.github/workflows/changelog.yml, .github/workflows/labeled-pr.yml, .github/workflows/release.yml, .github/workflows/static-analysis.yml, .github/workflows/tag-version.yml, .github/workflows/test-and-build.yml, CHANGELOG.md, hyp3_gamma/metadata/templates/rtc/readme.md.txt.j2
=> add pixel spacing information to RTC readme

hyp3_gamma/metadata/templates/rtc/readme.md.txt.j2
This PR changes the format of the pixel spacing to display an integer value
=> set pixel spacing to integer format

.github/workflows/changelog.yml, .github/workflows/labeled-pr.yml, .github/workflows/release.yml, .github/workflows/static-analysis.yml, .github/workflows/tag-version.yml, .github/workflows/test-and-build.yml, CHANGELOG.md, hyp3_gamma/metadata/templates/rtc/readme.md.txt.j2
=> Release v5.7.5

setup.py
=> remove water_map entrypoint from setup.py

CHANGELOG.md, Dockerfile, hyp3_gamma/__main__.py, setup.py
=> Release v6.0.0

CHANGELOG.md, hyp3_gamma/__main__.py, hyp3_gamma/insar/ifm_sentinel.py
=> Adjustable adf avo

CHANGELOG.md, hyp3_gamma/__main__.py, hyp3_gamma/insar/ifm_sentinel.py
=> Release v6.1.0

CHANGELOG.md, hyp3_gamma/__main__.py
=> modify code to allow users to process 20 meter resolution RTC

hyp3_gamma/metadata/templates/rtc/readme.md.txt.j2
=> modify readme.md.txt.j2 to reflect the addition of 20 meter resolution

.github/workflows/changelog.yml, .github/workflows/labeled-pr.yml, .github/workflows/release.yml, .github/workflows/static-analysis.yml, .github/workflows/tag-version.yml, .github/workflows/test-and-build.yml, CHANGELOG.md, hyp3_gamma/__main__.py, hyp3_gamma/metadata/templates/rtc/readme.md.txt.j2
* For example, if the interface for a Lambda function has changed to expect different input,
then currently running jobs (which use the old step function definition) will call the new
function with the old input. So we must drain the job queue before deployment, so that the new
function is only called by the new step function definition.
=> Release V6.2.0

.github/workflows/release-template-comment.yml
To distinguish it from the release workflow.
=> Update job name in release checklist workflow

setup.py
This adds s3fs (and pyarrow) which was a requirement after the previous PR.
=> add s3fs to requirements

hyp3_gamma/water_mask.py
The previous PR's in attempt to fix #507 have introduced similar errors where certain regions end up with blank water masks. This PR's method has been evaluated against the regions which previously had errors, and they all appear to be correct.
=> Fix Errors in Water Masking

CHANGELOG.md, README.md, environment.yml, hyp3_gamma/__main__.py, hyp3_gamma/insar/ifm_sentinel.py, hyp3_gamma/rtc/rtc_sentinel.py, setup.py
This will likely be a major release because it will add two new required CLI options / environment variables (for the ESA creds), so will break existing workflows.
TODO:
=> Release v7.0.0

hyp3_gamma/water_mask.py
=> add buffer 0.15 to original extent in WGS84 and clip in WGS84

hyp3_gamma/water_mask.py, tests/data/water_mask_output_info.txt
The previous method of cropping produces images that are the wrong size for gamma. This PR fixes that.
=> New Cropping Method for the New Water Masks

.github/dependabot.yml, .github/workflows/changelog.yml, .github/workflows/create-jira-issue.yml, .github/workflows/labeled-pr.yml, .github/workflows/release-template-comment.yml, .github/workflows/release.yml, .github/workflows/static-analysis.yml, .github/workflows/tag-version.yml, .github/workflows/test-and-build.yml, CHANGELOG.md, requirements.txt
passing rtc test: https://github.com/ASFHyP3/hyp3-testing/actions/runs/9769470278
passing insar test: https://github.com/ASFHyP3/hyp3-testing/actions/runs/9769469375
=> Release v1.8.4

CHANGELOG.md, README.md, hyp3_gamma/__main__.py, hyp3_gamma/insar/ifm_sentinel.py, hyp3_gamma/rtc/rtc_sentinel.py, requirements.txt
Golden tests:
* (Failed, but with insignificant differences) RTC: https://github.com/ASFHyP3/hyp3-testing/actions/runs/10310658744/job/28542799940
* (Passed) InSAR: https://github.com/ASFHyP3/hyp3-testing/actions/runs/10310656583/job/28542793670
=> Release v9.0.0

.github/workflows/changelog.yml, .github/workflows/create-jira-issue.yml, .github/workflows/labeled-pr.yml, .github/workflows/release-template-comment.yml, .github/workflows/release.yml, .github/workflows/static-analysis.yml, .github/workflows/tag-version.yml, .github/workflows/test-and-build.yml, CHANGELOG.md, hyp3_gamma/__main__.py, hyp3_gamma/dem.py, hyp3_gamma/insar/ifm_sentinel.py, hyp3_gamma/insar/unwrapping_geocoding.py, hyp3_gamma/metadata/create.py, hyp3_gamma/metadata/insar.py, hyp3_gamma/metadata/rtc.py, hyp3_gamma/metadata/util.py, hyp3_gamma/rtc/rtc_sentinel.py, hyp3_gamma/water_mask.py, pyproject.toml, requirements-develop.txt, tests/metadata/test_insar_gamma.py, tests/metadata/test_rtc_gamma.py, tests/test_water_mask.py
=> Release v9.0.2
