ASFHyP3/hyp3-gamma

hyp3_rtc_gamma/__main__.py

This allow `--help` to fall though to the processing entrypoint and `++help` will provide the `entry` fn help

Use special prefix chars for entry

---

hyp3_rtc_gamma/__main__.py
hyp3_rtc_gamma/rtc_sentinel.py

Previous method of builing the output from literals and granule name is brittle, instead this allows rtc_sentinel to tell the entrypoint where it put files

get output directory from rtc_sentinel

---

hyp3_rtc_gamma/rtc_sentinel.py

from mk_geo_radcal's usage docs:
`-j           (option) do not use layover-shadow map in the calculation of pixel_area`
Verified the -j flag is now absent for both the co-pol and cross-pol calls.  Didn't test the matching case, but I'm comfortable merging.
```
Running command: mk_geo_radcal S1A_IW_RT30_20170708T161200_G_gpn.VV.mgrd S1A_IW_RT30_20170708T161200_G_gpn.VV.mgrd.par area.dem area.dem.par geo_VV/area.dem geo_VV/area.dem_par geo_VV image 30 0 -p -n 1 -q -c -g 
Running command: mk_geo_radcal S1A_IW_RT30_20170708T161200_G_gpn.VV.mgrd S1A_IW_RT30_20170708T161200_G_gpn.VV.mgrd.par area.dem area.dem.par geo_VV/area.dem geo_VV/area.dem_par geo_VV image 30 3 -p -n 1 -q -c -g 
Running command: mk_geo_radcal S1A_IW_RT30_20170708T161200_G_gpn.VH.mgrd …
```

drop -j flag from calls to mk_geo_radcal

---

conda-env.yml
setup.py

This pulls in the latest `hpy3lib` and `hpy3proclib`, which includes a `nodata` bugfix for DEMs and a `default_rtc_resolution` bugfix, respectively.
---
Needs asfadmin/hyp3-lib#175 and asfadmin/hyp3-proc-lib#4

Pull in hyp3 libs bugfixes

---

.github/pull_request_template.md
.github/workflows/release.yml
.github/workflows/test-and-build.yml
CHANGELOG.md
Dockerfile
setup.py

* Change all references of `asfadmin` github org to new `ASFHyP3` org
* Update the release workflow to use the `CHANGELOG.md` when writing the release notes
* Removes the `v` prefix on version numbers inside the `CHANGELOG.md` as `antonyurchenko/git-release` can only handle prefixes on git tags and not within the `CHANGELOG.md`

Organizational updates

---

tests/test_v2.py

When I removed `__main__.download_file()` in favor of `hyp3lib.fetch.download_file()`, I accidentally removed the wrong test.

removed the wrong test

---

.github/PULL_REQUEST_TEMPLATE/release.md
.gitignore
CHANGELOG.md
Dockerfile

* Update pull request release template
* Fix typo in changelog
* add `tcsh` to Dockerfile because GAMMA uses it (only need for play inside the container, not actually used by rtc code)
* Add GAMMA and MapReady to git ignore

Minor cleanup

---

CHANGELOG.md
hyp3_rtc_gamma/__main__.py
hyp3_rtc_gamma/rtc_sentinel.py

Removes code for producing flattened backscatter tifs introduced in https://github.com/ASFHyP3/hyp3-rtc-gamma/commit/ea08afac67c34c0f6064ccc57f586cc4bd03096c
Replaces the existing `--area` parameter with `--include-scattering-area`, which results in a `_area.tif` being included in the output product directory and/or zip file.
This approach avoids further patching `mk_geo_radcal` by waiting to generate the area map until after the co-pol call to `mk_geo_radcal` mode 3 has completed.
Product readme in hyp3-metadata-templates should be updated to include a description of the additional output file.
Need to confirm with Kirk whether hyp3-metadata-templates should also create an ArcGIS-compatible .xml metadata file for the area tif, and if that should include a thumbnail image.
Product guide …

draft of --include-scattering-area

---

conda-env.yml

Docker runtime is python 3.6.9, setup.py specifies 3.6

downgrade to python 3.6 in conda environment

---

CHANGELOG.md
hyp3_gamma/__main__.py
hyp3_gamma/rtc/rtc_sentinel.py
hyp3_gamma/util.py
tests/test_util.py

`--dem-name legacy S1A_IW_SLC__1SSV_20150621T120220_20150621T120232_006471_008934_72D8` passes golden testing compared to `main` (with all other parameters as the defaults).
Similarly, `--dem-name copernicus S1A_IW_SLC__1SSV_20150621T120220_20150621T120232_006471_008934_72D8` passes golden testing compared to `develop`.

Add dem_name option for RTC supporting copernicus or legacy

---

CHANGELOG.md
hyp3_gamma/rtc/rtc_sentinel.py

`--dem-name legacy S1A_IW_SLC__1SSV_20150621T120220_20150621T120232_006471_008934_72D8` passes golden testing compared to `main` (with all other parameters as the defaults)
`--bbox -92 14.2 -91.85 14.35 --dem-name legacy S1A_IW_SLC__1SSV_20150621T120220_20150621T120232_006471_008934_72D8.SAFE` passes compared to `main`
`--dem-name copernicus S1A_IW_SLC__1SSV_20150621T120220_20150621T120232_006471_008934_72D8` passes compared to `develop`
`--bbox` with `--dem-name copernicus` doesn't subset to the exact bbox like with `--dem-name legacy`, but will limit the dem mosaic to tiles within 0.15 degrees of the bbox.
`--dem` now feeds the GeoTIFF through `dem_import` with EGM2008 correction and the default NoData parameters.  Still requires a UTM projection (or at least something with a pixel size …

restore --dem and --bbox options

---

CHANGELOG.md
hyp3_gamma/__main__.py
hyp3_gamma/insar/etc/README_InSAR_GAMMA.txt

Updated README content is taken from https://github.com/ASFHyP3/hyp3-metadata-templates/pull/72
My impression Is "Include Wrapped Phase" is the best user-facing label for this option, but different versions of the README also refer to it as the "Wrapped Interferogram" or simply the "Wrapped GeoTIFF".  I'm open to alternatives if anyone has strong opinions.

expose include_wrapped_phase option for InSAR in hyp3 entrypoint

---

.github/workflows/test-and-build.yml

Version incorrectly specified because the tags aren't checked out before copying the repo into the container.

Fix incorrect hyp3-gamma version in container

---

hyp3_gamma/water_mask.py

eliminates RuntimeError exception when running with gdal=2.2.3 (likely fixed in gdal>=2.3)
```
>>> from hyp3_gamma.water_mask import create_water_mask
>>> create_water_mask('S1BB_20200613T003027_20200625T003028_VVP012_INT80_G_ueF_F13E_unw_phase.tif', 'mask.tif')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.6/dist-packages/hyp3_gamma/water_mask.py", line 27, in create_water_mask
gdal.Rasterize(dst_ds, mask_location, burnValues=[1])
File "/usr/local/lib/python3.6/dist-packages/osgeo/gdal.py", line 1092, in Rasterize
return wrapper_GDALRasterizeDestDS(destNameOrDestDS, srcDS, opts, callback, callback_data)
File "/usr/local/lib/python3.6/dist-packages/osgeo/gdal.py", line 3254, in wrapper_GDALRasterizeDestDS
return …
```

set OGR_ENABLE_PARTIAL_REPROJECTION=TRUE in create_water_mask

---

Dockerfile

Now that geopandas is a `hyp3_gamma` requirement, `pandas==0.23` is installed, but then immediately uninstalled and upgraded to `1.1.5` on line 41 when installing `hyp3_gamma`:
```
#11 21.94   Attempting uninstall: pandas
#11 21.94     Found existing installation: pandas 0.23.0
#11 22.19     Uninstalling pandas-0.23.0:
#11 22.21       Successfully uninstalled pandas-0.23.0
#11 30.70 Successfully installed MarkupSafe-2.0.1 attrs-21.2.0 boto3-1.18.3 botocore-1.21.3 certifi-2021.5.30 charset-normalizer-2.0.3 click-8.0.1 click-plugins-1.1.1 cligj-0.7.2 fiona-1.8.20 geopandas-0.9.0 hyp3-gamma-4.6.2.dev44+g10cff75 hyp3-metadata-1.2.4 hyp3lib-1.6.8 idna-3.2 imageio-2.9.0 importlib-metadata-4.6.1 jinja2-3.0.1 jmespath-0.10.0 lxml-4.6.3 munch-2.5.0 numpy-1.19.5 pandas-1.1.5 patsy-0.5.1 …
```

remove pandas==0.23 install from dockerfile

---

hyp3_gamma/water_mask.py
tests/test_dem.py
tests/test_water_mask.py

~~`split_geometry_on_antimeridian` needs a couple of test cases, simple rectangle crossing the meridian and one not crossing the meridian should suffice.~~ (done)
- `{"type":"Polygon","coordinates":[[[177.8322245,52.4800782],[178.0102838,50.8930535],[-177.2308671,50.9995481],[-177.2391496,52.5927883],[177.8322245,52.4800782]]]}` is the polygon of the meridian granule I was using for local testing, a lower-precision version of that should work
Partially duplicates `hyp3_gamma.dem.get_geometry_from_kml`, I'm open to any suggestions to consolidate them.
Also open to alternatives to `ogr2ogr` to do the splitting itself.

split granule extent on antimeridian before subsetting global shapefile

---

hyp3_gamma/insar/unwrapping_geocoding.py

The `rasdt_pwr` call to create the `unw_phase.png` browse image was incorrectly implemented in the [initial gamma upgrade PR](https://github.com/ASFHyP3/hyp3-gamma/pull/303):
```
< rasrmg {ifgname}.adf.unw {mmli} {width} 1 1 0 1 1 0.33333 1.0 .35 0.0 - {ifgname}.adf.unw.ras
> rasdt_pwr {ifgname}.adf.unw {mmli} {width} - - - - - - 1 rmg.cm {ifgname}.adf.unw.ras
```
The fringes were incorrectly wrapped to mod `1.0` instead of mod `12*pi`. This fixes the wrapping. The fixed fringes start at a different value compared with production, but I'm comfortable leaving that unaddressed.
Production:
Test:
Fixed:

wrap unw_phase.png at 12*pi

---

CHANGELOG.md
hyp3_gamma/__main__.py

It is now possible to inject Earthdata username and password as environment variables, though cli args take precedence.

Earthdata creds

---

Dockerfile
environment.yml
setup.py

The apt install puts v1.17.4 in the container. With this approach, the subsequent pip install doesn't change numpy and correctly brings in pandas 1.3.5.
Numpy 1.17.4 isn't available via conda-forge, but 1.17.5 is, hence not pinning either setup.py or environment.yml to a specific patch version.

upgrade pip and pin numpy version to match system ubuntu version

---

CHANGELOG.md

Square brackets are required around the version number for our actions to work, as per the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) spec
Also, `Security` section is for vulnerabilities, where allowing EDL username/password via env variables is a user feature we added.

Fix changelog syntax

---

Dockerfile

This is an *extremely* short term fix to pin the asf-tools environment used for water mapping back to the last known working environment and also keep `hpy3-gamma` up to date. 
It's directly copying the asf-tools env, so there's no dependency updates or changes and it should function *exactly* like in v5.1.2
This also paves the way for a medium term, or possibly long term, way to manage and develop these environments separately:
* In ASFHyP3/asf-tools#94 we're developing an asf-tools container which can become the source of truth for the asf-tools environment here and this container would always copy in the `latest` asf-tools env out of that container
* asf-tools development can be managed entirely in the asf-tools space
* hyp3-gamma develop can continue without worrying about the water …

Rework how we bring in the asf-tools conda env

---

hyp3_gamma/insar/unwrapping_geocoding.py
tests/insar/test_unwrapping_geocoding.py

Changes the signature of `ref_point_with_max_cc()` to take a data array instead of a file name to make testing significantly more straightforward. Adds tests for the function.

add test for ref_point_with_max_cc

---

CHANGELOG.md
hyp3_gamma/insar/unwrapping_geocoding.py
tests/insar/test_unwrapping_geocoding.py

We have updated the InSAR code to set the amplitude threshold for the validity mask to 0.0. In addition, the reference point is now selected based on the neighborhood values, ensuring that the high coherence pixel is amidst other high coherence pixels.

Release updated InSAR code with new validity thresholds and reference point calculation

---

CHANGELOG.md
hyp3_gamma/insar/unwrapping_geocoding.py

This PR solves the issue about the reference point indexes. In previous version, we get fooled by the output of the mcf command. It always reports the reference point as the azlin+1, rpix+1, where azlin and rpix are the arguments of the mcf, and are reference point indexes starting from 0. After testing, we found that the sarpix_coord command accepts the reference point (azlin, rpix) which is based on indexes starting from 0. So we correct the previous code, and output the reference point  indexes stating from 0 in the meta text. We need explain the reference point in the InSAR Product Guide and/or README file.

fix the error arguments azlin and rpix in the sarpix_coord command

---

hyp3_gamma/__main__.py

fixes water_map jobs failing with `flood_map: error: argument --known-water-threshold: invalid float value: '30.0--iterative-bounds'`

fix typo in call to flood_map

---

.github/workflows/test-and-build.yml
CHANGELOG.md
Dockerfile
environment.yml
setup.py

Only significant change between the 202206030 linux installation guide and the one from 20210701 is the addition of `python3-packaging`. The 20220630 installation guides for ubuntu 20.04 and 22.04 are byte-for-byte identical.
I've run rtc for `S1A_IW_SLC__1SSV_20150621T120220_20150621T120232_006471_008934_72D8` and insar for `S1A_IW_SLC__1SSV_20150621T120220_20150621T120232_006471_008934_72D8+S1A_IW_SLC__1SSV_20150504T120217_20150504T120229_005771_00769E_EF9A` on my local machine with all default options. They both run to completion and produce output that looks consistent to the naked eye in a GIS.
Will need to run a full test suite to exercise all the parameter options and code paths.

upgrade to gamma 20220630

---

hyp3_gamma/water_mask.py

Here's a crude and quick fix to the `ERROR 1: GeoJSON object too complex, please see the OGR_GEOJSON_MAX_OBJ_SIZE environment option` errors we see when processing these scenes over the Aegean Sea:
- `S1B_IW_SLC__1SDV_20201115T162313_20201115T162340_024278_02E29D_5C54`
- `S1A_IW_SLC__1SDV_20201203T162353_20201203T162420_035524_042744_6D5C`
The `OGR_GEOJSON_MAX_OBJ_SIZE` setting is specific to the GDAL GeoJSON driver, documentation is at https://gdal.org/drivers/vector/geojson.html#configuration-options
We're using GeoJSON for the temp file out of convenience, we might be able to avoid this issue by using any other [GDAL-supported vector format](https://gdal.org/drivers/vector/index.html).
Alternatively, if we stick with GeoJSON, it would be nice to set `OGR_GEOJSON_MAX_OBJ_SIZE` based on …

set OGR_GEOJSON_MAX_OBJ_SIZE in create_water_map

---

hyp3_gamma/water_mask.py

Resolves `ERROR 1: Full reprojection failed, but partial is possible if you define OGR_ENABLE_PARTIAL_REPROJECTION configuration option to TRUE` issue in call to gdal.Rasterize that resulted in not all land bodies being successfully recognized in the water mask:
Setting this option gives the desired mask for this region:

set OGR_ENABLE_PARTIAL_REPROJECTION=YES in create_water_map

---

CHANGELOG.md
environment.yml
hyp3_gamma/__main__.py
setup.py

[pkg_resources](https://setuptools.pypa.io/en/latest/pkg_resources.html) provided by setuptools has a depreciation warning in their docs stating:
> :warning: Attention
> 
> Use of pkg_resources is discouraged in favor of [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html), and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Please consider using those libraries instead of pkg_resources.
This updates the entry_point loading method to use [`importlib.metadata.entry_points()`](https://docs.python.org/3.10/library/importlib.metadata.html#entry-points), which is …

Use importlib.metadata instead of depreciated pkg_resources

---

CHANGELOG.md
hyp3_gamma/__main__.py

GAMMA programs use OpenMP for parallel processing. The number of threads used range from 3-12+ from program to program. This can lead to severe CPU contention when running multiple GAMMA jobs on the same machine, drastically increasing the run time of those jobs.
This PR adds a command line parameter to the `main()` entrypoint to set the `OMP_NUM_THREADS` environment variable. See https://www.ibm.com/docs/en/zos/2.2.0?topic=suce-environment-variables-openmp
This allows running multiple jobs on the same machine without CPU contention. For example, running two jobs on an 8 core machine would typically result in both jobs trying to use all 8 cores at the same time. Setting `++omp-num-threads=4` for each job would limit the total demand to match the number of available cores and eliminates …

add ++omp-num-threads parameter to main() entrypoint

---

CHANGELOG.md
Dockerfile
hyp3_gamma/__main__.py

Once HyP3 uses asf-tools directly to run the water map and flood depth code, we can drop all that from this container. 
Will need to test that RTC and InSAR jobs still work.

drop asf-tools env from container and watermap hyp3 entrypoint

---

hyp3_gamma/__main__.py

```
$ adf 20230227_20230311.diff0.man 20230227_20230311.diff0.man.adf 20230227_20230311.adf.cc 3392 0.0 - 5
*** Adaptive interferogram bandpass filter based on the power spectral density ***
...
ERROR: invalid value for filter exponent:    0.000
```
```ipython
n [1]: def phase_filter_valid_range(x: str) -> float:
...:     x = float(x)
...:     if 0.0 < x <= 1.0:
...:         return x
...:     raise ValueError(f'{x} not in range (0.0, 1.0]')
...: 
In [2]: phase_filter_valid_range(0.0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
...
ValueError: 0.0 not in range (0.0, 1.0]
```
For ranges in "maths", convention is `()` for exclusive endpoints, `[]` for inclusive: …

Set phase filter parameter minumum to exclusive

---

hyp3_gamma/metadata/templates/macros.j2
hyp3_gamma/metadata/templates/rtc/readme.md.txt.j2

Minor futzing with the Jinja gets both COP30 and legacy dems to look right.

Fix RTC README whitespace

---

environment.yml

This will allow us to test the `hyp3lib` orbit fetching changes using the `hyp3-gamma` test container.

Temporarily pin `hyp3lib` to `develop` branch

---

hyp3_gamma/insar/ifm_sentinel.py
hyp3_gamma/rtc/rtc_sentinel.py

This will allow testing the new `hyp3lib` orbit fetching implementation on `hyp3-test`. Afterwards, we can either revert this PR (if we're not going to release the new orbit fetching implementation), or finalize the implementation from this PR, add a Changelog entry, and release the changes.

Use the new orbit fetching interface
